# Generated by Django 2.2.14 on 2020-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='product_name')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='vendor code')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='vendor code')),
                ('image_path', models.TextField(max_length=200, verbose_name='img_path')),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='vendor code')),
                ('provider', models.CharField(max_length=50, verbose_name='vendor code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
