# Generated by Django 2.2.13 on 2020-08-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_id',
            field=models.CharField(default=None, max_length=50, verbose_name='vendor code'),
        ),
    ]
