# Generated by Django 2.2.14 on 2020-07-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providers',
            options={'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='vendor_code',
        ),
        migrations.AlterField(
            model_name='providers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='provider',
            field=models.CharField(max_length=50, verbose_name='Provider name'),
        ),
    ]
