# Generated by Django 2.2.14 on 2020-07-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200719_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='prod_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AddField(
            model_name='providers',
            name='prod_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
