# Generated by Django 2.2.14 on 2020-07-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200719_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providers',
            name='vendor_code',
        ),
    ]
