# Generated by Django 2.2.14 on 2020-07-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_providers_vendor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='prod_id',
            new_name='vendor_code',
        ),
        migrations.RenameField(
            model_name='providers',
            old_name='prod_id',
            new_name='vendor_code',
        ),
    ]
