# Generated by Django 2.2.14 on 2020-07-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200719_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providers',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='price',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Providers'),
        ),
        migrations.AddField(
            model_name='providers',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Provider name'),
        ),
        migrations.AddField(
            model_name='providers',
            name='telephone',
            field=models.CharField(default=None, max_length=12, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='providers',
            name='zip_code',
            field=models.CharField(default=None, max_length=6, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=None, max_length=50, verbose_name='vendor code'),
        ),
        migrations.CreateModel(
            name='ProviderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Providers')),
                ('vendor_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
