# Generated by Django 2.2.14 on 2020-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200722_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='vendor_code',
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='price'),
        ),
    ]
