# Generated by Django 2.2.14 on 2020-07-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200722_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Providers',
            new_name='Supplier',
        ),
        migrations.RenameModel(
            old_name='ProviderProduct',
            new_name='SupplierProduct',
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='provider',
            new_name='supplier_name',
        ),
    ]
