# Generated by Django 2.2.14 on 2020-07-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200728_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_path',
            field=models.ImageField(blank=True, default='no_image_available.png', upload_to=''),
        ),
    ]
