# Generated by Django 2.2 on 2020-07-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200728_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='vendor code'),
        ),
    ]
