# Generated by Django 2.2 on 2020-08-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200731_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='telephone',
        ),
    ]
