# Generated by Django 3.1 on 2020-08-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_supplier_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_code',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='vendor_code',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='vendor_code',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='supplier_name',
            new_name='supplier',
        ),
    ]
