# Generated by Django 2.2 on 2020-08-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200809_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(default='no_image_available-1.png', upload_to=''),
        ),
    ]
