# Generated by Django 3.1 on 2020-08-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200809_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, default='no_image_available-1.png', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.image'),
        ),
    ]
